In [9]:
import numpy as np
import pandas as pd

# Creating a DataFrame

In [10]:
data = {
    'Name': ['sonu','pankaj','gaurav','anuj'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [11]:
df

     Name  Age      City  Salary
0    sonu   28  New York   65000
1  pankaj   34     Paris   70000
2  gaurav   29    Berlin   62000
3    anuj   42    London   85000

In [15]:
data_list = [
    ['Sonu', 28, 'New York', 65000],
    ['anuj', 34, 'Paris', 70000],
    ['pankaj', 29, 'Berlin', 62000],
    ['gaurav', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)

In [16]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

### Selection and indexing of Columns

In [17]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [18]:
df2['Name']

0      Sonu
1      anuj
2    pankaj
3    gaurav
Name: Name, dtype: str

In [19]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [20]:
df2[["Name","Salary"]]

     Name  Salary
0    Sonu   65000
1    anuj   70000
2  pankaj   62000
3  gaurav   85000

### Creating a new column

In [21]:
df2["Designation"] = ["Engineer","CA","Doctor","Engineer"]

In [22]:
df2

     Name  Age      City  Salary Designation
0    Sonu   28  New York   65000    Engineer
1    anuj   34     Paris   70000          CA
2  pankaj   29    Berlin   62000      Doctor
3  gaurav   42    London   85000    Engineer

### Removing Column

In [23]:
df2.drop("Designation",axis=1)

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [24]:
df2

     Name  Age      City  Salary Designation
0    Sonu   28  New York   65000    Engineer
1    anuj   34     Paris   70000          CA
2  pankaj   29    Berlin   62000      Doctor
3  gaurav   42    London   85000    Engineer

In [25]:
df2.drop("Designation",axis=1,inplace=True)

In [26]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [28]:
df2.drop(["City","Salary"],axis=1)

     Name  Age
0    Sonu   28
1    anuj   34
2  pankaj   29
3  gaurav   42

In [29]:
df2.drop(1,axis=0)

     Name  Age      City  Salary
0    Sonu   28  New York   65000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [30]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

### Selecting Rows

In [31]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [32]:
df2.loc[0]

Name          Sonu
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [34]:
df2.loc[[0,2]]

     Name  Age      City  Salary
0    Sonu   28  New York   65000
2  pankaj   29    Berlin   62000

In [36]:
df2.iloc[3]

Name      gaurav
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selcting Subsets of Rows and Columns

In [37]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [38]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [39]:
df2.loc[[2,3]][['Age','City']]

   Age    City
2   29  Berlin
3   42  London

In [40]:
df2.loc[[1,2]][['Age','City']]

   Age    City
1   34   Paris
2   29  Berlin

### Conditional Selection

In [41]:
df2

     Name  Age      City  Salary
0    Sonu   28  New York   65000
1    anuj   34     Paris   70000
2  pankaj   29    Berlin   62000
3  gaurav   42    London   85000

In [42]:
#  i only want to see those people whose age is above 30
df2[df2['Age'] > 30]

     Name  Age    City  Salary
1    anuj   34   Paris   70000
3  gaurav   42  London   85000

In [45]:
#  i only want to see whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  anuj   34  Paris   70000