In [1]:
import numpy as np
import pandas as pd

## Merging 2 dataframes

In [3]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['sonu', 'Aman', 'Pankaj', 'kuldeep', 'Boby'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id     name department
0            1     sonu         HR
1            2     Aman         IT
2            3   Pankaj    Finance
3            4  kuldeep         IT
4            5     Boby         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [6]:
pd.merge(employees,salaries)

   employee_id    name department  salary  bonus
0            1    sonu         HR   60000   5000
1            2    Aman         IT   80000  10000
2            3  Pankaj    Finance   65000   7000

In [7]:
pd.merge(employees,salaries,on="employee_id")

   employee_id    name department  salary  bonus
0            1    sonu         HR   60000   5000
1            2    Aman         IT   80000  10000
2            3  Pankaj    Finance   65000   7000

In [8]:
pd.merge(employees,salaries,on="employee_id",how='inner')

   employee_id    name department  salary  bonus
0            1    sonu         HR   60000   5000
1            2    Aman         IT   80000  10000
2            3  Pankaj    Finance   65000   7000

In [9]:
pd.merge(employees,salaries,on="employee_id",how='outer')

   employee_id     name department   salary    bonus
0            1     sonu         HR  60000.0   5000.0
1            2     Aman         IT  80000.0  10000.0
2            3   Pankaj    Finance  65000.0   7000.0
3            4  kuldeep         IT      NaN      NaN
4            5     Boby         HR      NaN      NaN
5            6      NaN        NaN  70000.0   8000.0
6            7      NaN        NaN  90000.0  12000.0

In [10]:
pd.merge(employees,salaries,on="employee_id",how='left')

   employee_id     name department   salary    bonus
0            1     sonu         HR  60000.0   5000.0
1            2     Aman         IT  80000.0  10000.0
2            3   Pankaj    Finance  65000.0   7000.0
3            4  kuldeep         IT      NaN      NaN
4            5     Boby         HR      NaN      NaN

In [11]:
pd.merge(employees,salaries,on="employee_id",how='right')

   employee_id    name department  salary  bonus
0            1    sonu         HR   60000   5000
1            2    Aman         IT   80000  10000
2            3  Pankaj    Finance   65000   7000
3            6     NaN        NaN   70000   8000
4            7     NaN        NaN   90000  12000

## Concatination of 2 dataframes

In [12]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [13]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [17]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## Joining of 2 dataframes

In [18]:
df1 = pd.DataFrame({
    'name': ['sonu', 'arjun', 'nakul']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [19]:
df1

    name
1   sonu
2  arjun
3  nakul

In [20]:
df2

   score
2     85
3     90
4     75

In [21]:
df1.join(df2)

    name  score
1   sonu    NaN
2  arjun   85.0
3  nakul   90.0

In [22]:
df1.join(df2, how='outer')

    name  score
1   sonu    NaN
2  arjun   85.0
3  nakul   90.0
4    NaN   75.0

In [23]:
df1.join(df2, how='inner')

    name  score
2  arjun     85
3  nakul     90

In [24]:
df2.join(df1)

   score   name
2     85  arjun
3     90  nakul
4     75    NaN