In [21]:
import numpy as np
import pandas as pd

## Pivot Tables

In [22]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['sonu', 'Mary', 'Boby', 'Alice', 'sonu', 'Mary', 'Boby', 'Alice', 'sonu', 'Mary',
            'Boby', 'Alice', 'sonu', 'Mary', 'Boby', 'Alice', 'sonu', 'Mary', 'Boby', 'Alice']
}

In [23]:
df  = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    790     37   sonu
1  2023-01-02       B   West    557     54   Mary
2  2023-01-03       C  North    151     90   Boby
3  2023-01-04       D  South    495     84  Alice
4  2023-01-05       A   East    755     65   sonu
5  2023-01-06       B   West    199     55   Mary
6  2023-01-07       C  North    864     72   Boby
7  2023-01-08       D  South    240     12  Alice
8  2023-01-09       A   East    644     75   sonu
9  2023-01-10       B   West    438     52   Mary
10 2023-01-11       C  North    946     49   Boby
11 2023-01-12       D  South    973     40  Alice
12 2023-01-13       A   East    816     91   sonu
13 2023-01-14       B   West    906     38   Mary
14 2023-01-15       C  North    669     49   Boby
15 2023-01-16       D  South    913     48  Alice
16 2023-01-17       A   East    791     92   sonu
17 2023-01-18       B   West    534     32   Mary
18 2023-01-19       C  North    146     13   Boby
19 2023-01-20       D  South    458     12  Alice

In [24]:
df['Month'] = df['Date'].dt.month_name()
df

         Date Product Region  Sales  Units    Rep    Month
0  2023-01-01       A   East    790     37   sonu  January
1  2023-01-02       B   West    557     54   Mary  January
2  2023-01-03       C  North    151     90   Boby  January
3  2023-01-04       D  South    495     84  Alice  January
4  2023-01-05       A   East    755     65   sonu  January
5  2023-01-06       B   West    199     55   Mary  January
6  2023-01-07       C  North    864     72   Boby  January
7  2023-01-08       D  South    240     12  Alice  January
8  2023-01-09       A   East    644     75   sonu  January
9  2023-01-10       B   West    438     52   Mary  January
10 2023-01-11       C  North    946     49   Boby  January
11 2023-01-12       D  South    973     40  Alice  January
12 2023-01-13       A   East    816     91   sonu  January
13 2023-01-14       B   West    906     38   Mary  January
14 2023-01-15       C  North    669     49   Boby  January
15 2023-01-16       D  South    913     48  Alice  January
16 2023-01-17       A   East    791     92   sonu  January
17 2023-01-18       B   West    534     32   Mary  January
18 2023-01-19       C  North    146     13   Boby  January
19 2023-01-20       D  South    458     12  Alice  January

In [25]:
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    790     37   sonu  January      Q1
1  2023-01-02       B   West    557     54   Mary  January      Q1
2  2023-01-03       C  North    151     90   Boby  January      Q1
3  2023-01-04       D  South    495     84  Alice  January      Q1
4  2023-01-05       A   East    755     65   sonu  January      Q1
5  2023-01-06       B   West    199     55   Mary  January      Q1
6  2023-01-07       C  North    864     72   Boby  January      Q1
7  2023-01-08       D  South    240     12  Alice  January      Q1
8  2023-01-09       A   East    644     75   sonu  January      Q1
9  2023-01-10       B   West    438     52   Mary  January      Q1
10 2023-01-11       C  North    946     49   Boby  January      Q1
11 2023-01-12       D  South    973     40  Alice  January      Q1
12 2023-01-13       A   East    816     91   sonu  January      Q1
13 2023-01-14       B   West    906     38   Mary  January      Q1
14 2023-01-15       C  North    669     49   Boby  January      Q1
15 2023-01-16       D  South    913     48  Alice  January      Q1
16 2023-01-17       A   East    791     92   sonu  January      Q1
17 2023-01-18       B   West    534     32   Mary  January      Q1
18 2023-01-19       C  North    146     13   Boby  January      Q1
19 2023-01-20       D  South    458     12  Alice  January      Q1

In [26]:
pd.pivot_table(df,values='Sales',index= 'Region',columns='Product')

Product      A      B      C      D
Region
East     759.2    NaN    NaN    NaN
North      NaN    NaN  555.2    NaN
South      NaN    NaN    NaN  615.8
West       NaN  526.8    NaN    NaN

In [27]:
pd.pivot_table(df,values='Sales',index= 'Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     790.0    NaN    NaN    NaN
North      NaN    NaN  669.0    NaN
South      NaN    NaN    NaN  495.0
West       NaN  534.0    NaN    NaN

In [28]:
pd.pivot_table(df,values='Sales',index= 'Region',columns='Product',aggfunc='sum')

Product       A       B       C       D
Region
East     3796.0     NaN     NaN     NaN
North       NaN     NaN  2776.0     NaN
South       NaN     NaN     NaN  3079.0
West        NaN  2634.0     NaN     NaN

In [29]:
pd.pivot_table(df,values='Sales',index= 'Region',columns='Product',aggfunc='std')

Product          A           B         C           D
Region
East     67.961018         NaN       NaN         NaN
North          NaN         NaN  384.6605         NaN
South          NaN         NaN       NaN  314.896332
West           NaN  254.997451       NaN         NaN

In [30]:
pd.pivot_table(df,values='Sales',index= 'Region',columns='Product',aggfunc='min')

Product      A      B      C      D
Region
East     644.0    NaN    NaN    NaN
North      NaN    NaN  146.0    NaN
South      NaN    NaN    NaN  240.0
West       NaN  199.0    NaN    NaN

In [31]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index= 'Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     759.2    NaN    NaN    NaN  72.0   NaN   NaN   NaN
North      NaN    NaN  555.2    NaN   NaN   NaN  54.6   NaN
South      NaN    NaN    NaN  615.8   NaN   NaN   NaN  39.2
West       NaN  526.8    NaN    NaN   NaN  46.2   NaN   NaN

## Cross Table

In [32]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0